insert into uea_unidade(unidade_nome, unidade_sigla, unidade_status)
values ('Escola Superior de Tecnologia', 'EST', 1),
('Escola Normal Superior', 'ENS', 1),
('Escola Superior de Ciencias Saude', 'ESA', 1),
('Escola Superior de Ciencias Sociais', 'ESO', 1),
('Escola Superior de Artes e Turismo', 'ESAT', 1),
('Centro de Estudos Superiores de Parintins', 'CESP', 1),
('Centro de Estudos Superiores de Tefé', 'CESP', 1),
('Centro de Estudos Superiores de Tabatinga', 'CESP', 1),
('Centro de Estudos Superiores de Itacoatiara', 'CESP', 1),
('Centro de Estudos Superiores de Lábrea', 'CESP', 1),
('Centro de Estudos Superiores de São Gabriel da Cachoeira', 'CESP', 1),
('Nucleo de Ensino Superior de Manacapuru', 'CESP', 1),
('Nucleo de Ensino Superior de Presidente Figueiredo', 'CESP', 1),
('Nucleo de Ensino Superior de Coari', 'CESP', 1),
('Nucleo de Ensino Superior de Maues', 'CESP', 1),
('Nucleo de Ensino Superior de Novo Aripuanã', 'CESP', 1),
('Nucleo de Ensino Superior de Caruari', 'CESP', 1),
('Nucleo de Ensino Superior de Manicoré', 'CESP', 1),
('Nucleo de Ensino Superior de Humaitá', 'CESP', 1),
('Nucleo de Ensino Superior de Boca do Acre', 'CESP', 1),
('Nucleo de Ensino Superior de Eirunepé', 'CESP', 1),
('Nucleo de Ensino Superior de Careiro Castanho', 'CESP', 1),
('Nucleo de Ensino Superior de Nova Olinda do Norte', 'CESP', 1),
('Unidade de São Paulo de Olivença', 'CESP', 1),
('Unidade de Anori', 'CESP', 1),
('Unidade de Iranduba', 'CESP', 1),
('Unidade de Borba', 'CESP', 1),
('Unidade de Fonte Boa', 'CESP', 1),
('Unidade de São Sebastião do Uatumã', 'CESP', 1),
('Unidade de Beruri', 'CESP', 1),
('Unidade de Tapauá', 'CESP', 1),
('Unidade de Autazes', 'CESP', 1),
('Unidade de Apuí', 'CESP', 1),
('Unidade de Tonantins', 'CESP', 1),
('Unidade de Jutaí', 'CESP', 1),
('Unidade de Japurá', 'CESP', 1),
('Unidade de Itapiranga', 'CESP', 1),
('Unidade de Barcelos', 'CESP', 1),
('Unidade de Maraã', 'CESP', 1),
('Unidade de Juruá', 'CESP', 1),
('Unidade de Nhamundá', 'CESP', 1),
('Unidade de Novo Airão', 'CESP', 1),
('Unidade de Boa Vista do Ramos', 'CESP', 1),
('Unidade de Barreirinha', 'CESP', 1),
('Unidade de Santo Antonio do Iça', 'CESP', 1),
('Unidade de Uarini', 'CESP', 1),
('Unidade de Nova Olinda do Norte', 'CESP', 1),
('Unidade de Envira', 'CESP', 1),
('Unidade de Ipixuna', 'CESP', 1),
('Unidade de Alvarães', 'CESP', 1),
('Unidade de Codajás', 'CESP', 1),
('Unidade de Benjamin Constant', 'CESP', 1),
('Centro de Estudos Superiores do Tropico Humido', 'CESP', 1),
('Unidade de Urucará', 'CESP', 1),
('Unidade de Itamarati', 'CESP', 1),
('Unidade de Manaquiri', 'CESP', 1),
('Unidade de Atalaia do Norte', 'CESP', 1),
('Unidade de Anamã', 'CESP', 1),
('Unidade de Canutama', 'CESP', 1),
('Unidade de Caapiranga', 'CESP', 1),
('Unidade de Guajará', 'CESP', 1),
('Unidade de Pauini', 'CESP', 1),
('Unidade de Santa Isabel do Rio Negro', 'CESP', 1),
('Unidade de Amaturá', 'CESP', 1);


